version: '3.4'
services:
  app:
    build: .
    command: sh -c 'LOG_LEVEL="DEBUG" uvicorn api.main:app --reload --host=0.0.0.0 --port=8000'
    ports:
     - 8000:8000
    volumes:
     - ./data:/code/data 